image: golang

stages:
  - build
  - release

variables:
  DOCKER_DRIVER: overlay2

build_snapshot:
  stage: build
  before_script:
    - echo "package model; const Version = \"`git describe --tags`\"" > src/domain/model/version.go
  script:
    - cd src
    - go mod tidy
    - go build pollywog.go
  artifacts:
    when: always
    paths:
      - src/pollywog
    expire_in: 1 week
  except:
    - tags

publish_release:
  stage: release
  before_script:
    - echo "package model; const Version = \"`git describe --tags`\"" > src/domain/model/version.go
  script:
    - cd src
    - go mod tidy
    - go build pollywog.go
  artifacts:
    when: always
    paths:
      - src/pollywog
    expire_in: 1 week
  only:
    - tags

semver:
  stage: release
  image: node:13
  before_script:
    - npm install @semantic-release/gitlab
    - cat $SEM_RELEASE_OPTIONS > .releaserc.yml
  script:
    - npx semantic-release -t \${version}
  only:
    - main
